### ISSUE TITLE
pgn/xpm icons with transparent background do not work with 2.6.6

### ISSUE THREAD

**Issue by bitstreamout** [fvwmorg/fvwm#11]
as subject says I've build 2.6.6 as replacement for 2.6.5 and all icons with transparent background  regardless if pgn or xpm are not shown correct.e.g. I'm using find1.xpm from fvwm2 for an icon:
![bug2](https://cloud.githubusercontent.com/assets/2392549/17356714/3fc119e6-5959-11e6-925d-0da366089f65.png).

Beside this icons will not correctly redrawed if the FvwmPager is used, that is if on an other screen some windows are placed on the same virtual location as the icons on the previous screen and I go back to this screen the icons as wel las there tiltle get not redrawed
![bug1](https://cloud.githubusercontent.com/assets/2392549/17356806/c03cea6e-5959-11e6-81f4-9122a525f3bc.png)

**Comment by bitstreamout** [comment]
By using diff between 2.6.5  and 2.6.6 code I dare to guess that something in the new event queue handling seems to be missed here?

**Comment by ThomasAdam** [comment]
Quite possibly.  Can you attach a link to your fvwm configuration as well, please?  I suspect I know what's going on, but wish to confirm.

**Comment by bitstreamout** [comment]
OK
[config.gz](https://github.com/fvwmorg/fvwm/files/398880/config.gz)

**Comment by ThomasAdam** [comment]
Yes, I bisected this down to: bd5c2aac8f61428c415507e2b1f0dbd952aa97ad

Will investigate...

**Comment by ThomasAdam** [comment]
Hi,

Can you please try the version of FVWM on the `ta/possible-fix-icon-pr` branch?  See:

https://github.com/fvwmorg/fvwm/tree/ta/possible-fix-icon-pr

This seems to help.

**Comment by bitstreamout** [comment]
Yep the commit [](https://github.com/fvwmorg/fvwm/commit/440d675d14412ec0a123d4c977534ab688229148.patch) does help a lot.

**Comment by bitstreamout** [comment]
IMHO this is fixed

**Comment by ThomasAdam** [comment]
Helps a lot is one thing, but are you able to say it's fixed?  Are there still artefacts on the screen which weren't there before, for example?

**Comment by ThomasAdam** [comment]
Reopening since this isn't fixed until I merge this to master.

**Comment by bitstreamout** [comment]
OK ... sometimes a few letter of icon titles are missed. Also if I restart fvwm and the regular title line includes a dot due to shell writing to XTerm a title with dot in the path then after the restart the window border misses title as well as the buttons.   Sometimes I see that if a windows gets focuse not all borders are highlighted but this very difficult to reproduce.  Nevertheless this was also with 2.6.5 and earlier.

**Comment by ThomasAdam** [comment]
Right, but you're happy my path fixes your original problem?  If so, I'll merge it in.  Thanks.

**Comment by bitstreamout** [comment]
Indeed I'm happy :)

**Comment by bitstreamout** [comment]
Here an example of missed title and also icon if on an other screen an window overlaps the icon ...
![bug3](https://cloud.githubusercontent.com/assets/2392549/17401964/ea90eb24-5a50-11e6-823c-c5f96fb8783c.png) and 
![bug4](https://cloud.githubusercontent.com/assets/2392549/17401970/f2f4b85e-5a50-11e6-9c6b-0bb3c50f2d53.png)

**Comment by bitstreamout** [comment]
The icons are places on the first screen of six and the the window overlaps the virtual position on the forth screen

**Comment by ThomasAdam** [comment]
OK.  Can you try the same branch again (I've forced-pushed an additional change out), which should address the icon title problem as well.  Cheers.

**Comment by bitstreamout** [comment]
Woh! ... yes this does resolve the behaviour ... and also now the title handling seems to more reliable that is a title does not go stuck anymore if I move an icons.

**Comment by bitstreamout** [comment]
I've an other missing/forgotten events with tagged root menus like this
![bug5](https://cloud.githubusercontent.com/assets/2392549/17403499/5a69356c-5a58-11e6-85e0-b7cbb22300c8.png) in comparision to 
![bug6](https://cloud.githubusercontent.com/assets/2392549/17403504/64b84170-5a58-11e6-82e8-5a578ce1a764.png)  ... the second layout is simply due the pointer has moved across the tagged menu :)

**Comment by ThomasAdam** [comment]
OK, same branch rebased.  Try again.  Any better?

**Comment by bitstreamout** [comment]
Yes,  this works also.  This rise the question of the usage of those expose functions ... maybe a better way would to combine equal expose events to only one if possible together with expiry date  ... an expose event collector instead of a garbage collector.

**Comment by bitstreamout** [comment]
also the context seems to play a role e.g. for animation?

**Comment by ThomasAdam** [comment]
Sure---the events are still flushed, it's just not done as often when the Pixmap is updated.  I'm not saying this is the final solution per-se, I'm just trying to check the behaviour is correct before I go ahead and make this change official.

**Comment by ThomasAdam** [comment]
Updated once more.  Please test; this is it now.  Looks good to me.

**Comment by bitstreamout** [comment]
I can second this
